import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/component/HeaderAllFile/Header";
import Footer from "@/component/HeaderAllFile/Footer";
import { CartProvider } from "@/context/cartContext";
import AuthProvider from "@/component/AuthProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <CartProvider>
            <div className="flex flex-col min-h-screen">
              <Header />

              <main className="flex-grow">{children}</main>

              <Footer />
            </div>
          </CartProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
